### PR TITLE
Add option to use ghcr in launch.py

### PR DESCRIPTION
**Pull request by Aphoh**
Adds the option for pushing containers to GHCR instead of GCP container registry into launch.py and adds a note in the TPU docs for it.

### CODE REVIEW

**Review by dlwh — APPROVED** [review]
lgtm but @rjpower could you weigh in?

**Comment by rjpower** [comment]
Seems fine, but what's the motivation? Does GCP not work for some use cases?

(The reason for using GCP was the concern that GHCR/Docker would be slow to load for larger pods or throttle/block the connection if e.g. they get 1000 requests at once.)

**Comment by dlwh** [comment]
(I'm guessing the reason is price sensitivity. A lot of TRC users are independent researchers.)

@Aphoh if you could fix merge conflicts (sorry about that!) i'll merge

**Comment by Aphoh** [comment]
@dlwh Nailed it, I'm as cheap as it gets when it comes to cloud stuff 😅. Merge conflicts fixed.

**Comment by dlwh** [comment]
i mean, i get it. I freaked out when some stray google process was costing us ~$500 month due to logging, and I have (some) grant money.

**Comment by dlwh** [comment]
thanks!

**Pull request merged**
