### PR TITLE
Introduce Mkdocs

### PR DESCRIPTION
**Pull request by Ivan-Zhou**
It's @dlwh 's work, but he might forget the last step of creating this PR :)

### CODE REVIEW

**Comment by dlwh** [comment]
how dare you insinuate that I forget things regularly! 😛

**Comment by Ivan-Zhou** [comment]
Need to install the following dependencies

```
pip install mkdocs
pip install mkdocstrings
pip install pymdown-extensions
pip install markdown-include
pip install mkdocs-include-markdown-plugin
```

Warning shown when running the server:

```
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - Announcement-Post.md
              - Getting-Started-Training.md
              - Installation.md
              - design/Data-Loader-Design.md
WARNING  -  A relative path to 'models.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'metrics.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'perturbations.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'scenarios.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'schemas.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'developer_setup.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'code.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  Documentation file 'index.md' contains a link to 'CONTRIBUTING.md' which is not found in the documentation files.
WARNING  -  Documentation file 'Announcement-Post.md' contains a link to 'figures/token_probabilities.png' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to '../examples/gpt2_example.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to '../config/gpt2_small.yaml' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/models/gpt2.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Installation.md' contains a link to 'docs/Getting-Started-TPU-VM.md' which is not found in the documentation files.
WARNING  -  Documentation file 'Installation.md' contains a link to 'docs/Getting-Started-CUDA.md' which is not found in the documentation files.
WARNING  -  Documentation file 'Overview.md' contains a link to '../src/levanter/models/gpt2.py' which is not found in the documentation files.
INFO     -  Documentation built in 5.88 seconds
INFO     -  [20:27:26] Watching paths for changes: 'docs', 'mkdocs.yml', 'README.md', 'src', 'examples', 'scripts', 'infra'
INFO     -  [20:27:26] Serving on http://127.0.0.1:8000/
```

**Comment by Ivan-Zhou** [comment]
LGTM now

**Comment by Ivan-Zhou** [comment]
image
The fact that Haliax is a stand-alone section is bit strange...

**Comment by Ivan-Zhou** [comment]
At a closer look, I think the following warnings haven't been solved yet. I will resolve them today:

```
WARNING  -  Documentation file 'Announcement-Post.md' contains a link to 'figures/token_probabilities.png' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to '../examples/gpt2_example.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to '../config/gpt2_small.yaml' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/models/gpt2.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Getting-Started-Training.md' contains a link to 'src/levanter/config.py' which is not found in the documentation files.
WARNING  -  Documentation file 'Installation.md' contains a link to 'docs/Getting-Started-TPU-VM.md' which is not found in the documentation files.
WARNING  -  Documentation file 'Installation.md' contains a link to 'docs/Getting-Started-CUDA.md' which is not found in the documentation files.
WARNING  -  Documentation file 'Overview.md' contains a link to '../src/levanter/models/gpt2.py' which is not found in the documentation files.
```

**Pull request merged**
